#!/usr/bin/python

import functools
import os.path
import subprocess

import SCons.Scanner.C

# Import variables.
Import(['env', 'src'])

# Our scanner.
scanner = SCons.Scanner.C.CScanner()

# Current working directory.
cwd = Dir(Dir(GetLaunchDir()).get_path(src))

# C++ extensions.
cpp_exts = {env[suffix] for suffix in {'PROGSUFFIX',
                                       'LIBSUFFIX',
                                       'SHLIBSUFFIX',
                                       'OBJSUFFIX',
                                       'SHOBJSUFFIX',
                                       'TESTSUFFIX'}}

# PDF extension.
pdf_ext = env['PDFSUFFIX']

# Unit test.
test_ext = env['TESTSUFFIX']

# List of supported extensions.
exts = cpp_exts | {pdf_ext} | {test_ext}

# Recursively find all of the object files that main depends on.
def get_dep_objects(main):
  def get_dep_sources(sources, out):
    if not sources:
      return out
    out |= sources
    dep_sources = set()
    for source in sources:
      for dep_header in source.get_implicit_deps(env, scanner, (src,)):
        dep_source = File(os.path.splitext(dep_header.get_path(src))[0] + '.cc')
        if dep_source.srcnode().exists() and dep_source not in out:
          dep_sources.add(dep_source)
    return get_dep_sources(dep_sources, out)
  return [env.Object(source) for source in get_dep_sources({main}, set())]

# Execute the test and check that the return code is 0.
def run_test(target, source, env):
  for test in source:
    subprocess.check_call(test.get_path())

# For each given target path, try to build it.
for target_path in BUILD_TARGETS:
  target = cwd.File(target_path)
  root, ext = os.path.splitext(target_path)
  # Validate that the file kind is supported.
  if ext not in exts:
    raise ValueError(
        'Invalid extension: "{ext}" (choose from {exts})'.format(
          ext=ext,
          exts=', '.join(['"{ext}"'.format(ext=ext) for ext in exts])))
  # Get the corresponding source files.
  source = None
  if ext == pdf_ext:
    source = cwd.File(root + '.latex')
  elif ext in cpp_exts:
    source = get_dep_objects(
                cwd.File(root + (test_ext if ext == test_ext else '') + '.cc'))
  # Choose the correct builder based on the target_path's extension.
  {env['PROGSUFFIX'] : env.Program,
   env['LIBSUFFIX']  : env.Library,
   env['SHLIBSUFFIX']: env.SharedLibrary,
   env['OBJSUFFIX']  : env.Object,
   env['SHOBJSUFFIX']: env.SharedObject,
   env['PDFSUFFIX']  : env.PDF,
   env['TESTSUFFIX'] : functools.partial(
                           env.Program,
                           LIBS=['gtest', 'gtest_main', 'pthread'])
  }[ext](target, source)
  # If target is a unit test, execute it.
  test = None
  if GetOption('test') and ext == test_ext:
    test = env.Command(
               None,
               target,
               Action(run_test, 'Running unit test: $SOURCE'))
  env.Alias(target_path, [target, test])

